name: codecov

on:
  push:
    branches:
    - "main"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  upload_to_codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.22.0'
        args: '-- --include-ignored'
    - name: upload to codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    - name: archive coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml