name: codecov

on:
  push:
    branches:
    - "main"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  upload_to_codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test
    - name: run tarpaulin
      uses: actions-rs/tarpaulin@v0.1
    - name: upload to codecov
      uses: codecov/codecov-action@v3
    - name: archive coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml